# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  test_domo:
    docker:
      - image: circleci/elixir:1.5

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Hex
          command: mix local.hex --force
          working_directory: ~/repo/apps/domo
      - run:
          name: Install Rebar
          command: mix local.rebar --force
          working_directory: ~/repo/apps/domo
      - run:
          name: Fetch dependencies
          command: mix deps.get
          working_directory: ~/repo/apps/domo
      - run:
          name: Run specs
          command: mix test
          working_directory: ~/repo/apps/domo

workflows:
  version: 2
  build:
    jobs:
      - test_domo
